[project]
name = "img-segmentation"
version = "0.1.0"
description = "Segmentation Repo to build from scratch U-Net Architecture"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.10.0",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pillow>=11.0.0",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "pyyaml>=6.0.3",
    "ultralytics>=8.4.159",
    "pytest>=9.1.1",
]
